[package]
name = "bevy_egui_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bevy_egui = "0.23.0"

# Using copy of catppuccin until it is updated to egui 0.23
# catppuccin-egui = "3.1.0"

